{"error": null, "issues": [{"address": 438, "code": "array.length += 1", "debug": "storage_1: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\ncalldata_DosNumber_32 + 4: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\ncalldata_DosNumber_0: 0x529f6f2d00000000000000000000000000000000000000000000000000000000\ncalldatasize_DosNumber: 0x4\nstorage_0: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\ncallvalue: 0x0\n", "description": "A possible integer overflow exists in the function `insertNnumbers(uint256,uint256)`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.", "filename": "/dataset/denial_of_service/dos_number.sol", "function": "insertNnumbers(uint256,uint256)", "lineno": 20, "title": "Integer Overflow ", "type": "Warning"}, {"address": 468, "code": "numElements++", "debug": "storage_0: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\nstorage_1: 0x0\ncalldata_DosNumber_32 + 4: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\ncalldata_DosNumber_0: 0x529f6f2d00000000000000000000000000000000000000000000000000000000\ncalldatasize_DosNumber: 0x4\ncallvalue: 0x0\n", "description": "A possible integer overflow exists in the function `insertNnumbers(uint256,uint256)`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.", "filename": "/dataset/denial_of_service/dos_number.sol", "function": "insertNnumbers(uint256,uint256)", "lineno": 22, "title": "Integer Overflow ", "type": "Warning"}, {"address": 483, "code": "array[numElements++]", "debug": "The exception is triggered under the following conditions:\n\nstorage_1: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\ncalldata_DosNumber_32 + 4: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\ncalldata_DosNumber_0: 0x529f6f2d00000000000000000000000000000000000000000000000000000000\ncalldatasize_DosNumber: 0x4\nstorage_0: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/dataset/denial_of_service/dos_number.sol", "function": "insertNnumbers(uint256,uint256)", "lineno": 22, "title": "Exception state", "type": "Informational"}, {"address": 583, "code": "contract DosNumber {\n\n    uint numElements = 0;\n    uint[] array;\n\n    function insertNnumbers(uint value,uint numbers) public {\n\n        // Gas DOS if number > 382 more or less, it depends on actual gas limit\n        // <yes> <report> DENIAL_OF_SERVICE\n        for(uint i=0;i<numbers;i++) {\n            if(numElements == array.length) {\n                array.length += 1;\n            }\n            array[numElements++] = value;\n        }\n    }\n\n    function clear() public {\n        require(numElements>1500);\n        numElements = 0;\n    }\n\n    // Gas DOS clear\n    function clearDOS() public {\n\n        // number depends on actual gas limit\n        require(numElements>1500);\n        array = new uint[](0);\n        numElements = 0;\n    }\n\n    function getLengthArray() public view returns(uint) {\n        return numElements;\n    }\n\n    function getRealLengthArray() public view returns(uint) {\n        return array.length;\n    }\n}", "debug": "storage_0: 0x10000000000000000000000000000000000000000005dc\nstorage_1: 0xb778ed5592f6fe4b7220ffffffffffffffffffffffffffce6ff0040008000148\ncalldata_DosNumber_0: 0x263e5d3c00000000000000000000000000000000000000000000000000000000\ncalldatasize_DosNumber: 0x4\ncallvalue: 0x0\n", "description": "A possible integer overflow exists in the function `clearDOS()`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.", "filename": "/dataset/denial_of_service/dos_number.sol", "function": "clearDOS()", "lineno": 9, "title": "Integer Overflow ", "type": "Warning"}], "success": true}